/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 2
 * @maxItems 2
 *
 * This interface was referenced by `ManualQuads`'s JSON-Schema
 * via the `definition` "point".
 */
export type Point = [number, number];

/**
 * Manual slide corners keyed by source filename or stem. Points are ordered top-left, top-right, bottom-right, bottom-left.
 */
export interface ManualQuads {
  /**
   * @minItems 4
   * @maxItems 4
   */
  [k: string]: [Point, Point, Point, Point];
}
