/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Points ordered top-left, top-right, bottom-right, bottom-left.
 *
 * @minItems 4
 * @maxItems 4
 *
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "quad".
 */
export type Quad = [Point, Point, Point, Point];
/**
 * @minItems 2
 * @maxItems 2
 *
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "point".
 */
export type Point = [number, number];

export interface SlideLensReport {
  input_dir: string;
  output_pdf: string;
  ratio: string;
  source_slide_ratio: string;
  output_page_ratio: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  size: [number, number];
  batch_summary: BatchSummary;
  slides: {
    index: number;
    source: string;
    output: string;
    quad: Quad;
    method: string;
    confidence: number;
    needs_review?: boolean;
    review_reasons?: string[];
    best_score?: number;
    second_best_score?: number | null;
    candidates_evaluated?: number;
    features?: Features;
    diagnostics?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
}
/**
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "batchSummary".
 */
export interface BatchSummary {
  preliminary_count: number;
  reliable_count: number;
  prior_count: number;
  priors: BatchPrior[];
}
/**
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "batchPrior".
 */
export interface BatchPrior {
  id: string;
  orientation: 'landscape' | 'portrait';
  normalized_quad: Quad;
  member_count: number;
  rms_deviation: number;
  consistency: number;
}
/**
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Features {
  edge_strength?: number;
  edge_support?: number;
  edge_continuity?: number;
  gradient_alignment?: number;
  inside_outside_difference?: number;
  region_consistency?: number;
  normalized_area?: number;
  geometry_validity?: number;
  aspect_prior?: number;
  batch_consistency?: number;
  [k: string]: unknown;
}
