/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Points ordered top-left, top-right, bottom-right, bottom-left.
 *
 * @minItems 4
 * @maxItems 4
 *
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "quad".
 */
export type Quad = [Point, Point, Point, Point];
/**
 * @minItems 2
 * @maxItems 2
 *
 * This interface was referenced by `SlideLensReport`'s JSON-Schema
 * via the `definition` "point".
 */
export type Point = [number, number];

export interface SlideLensReport {
  input_dir: string;
  output_pdf: string;
  ratio: string;
  source_slide_ratio: string;
  output_page_ratio: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  size: [number, number];
  slides: {
    index: number;
    source: string;
    output: string;
    quad: Quad;
    method: string;
    confidence: number;
    [k: string]: unknown;
  }[];
}
