"""Generate runtime product metadata from the repository source of truth."""

from __future__ import annotations

import argparse
import json
import pprint
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "metadata" / "product.json"
PYTHON_OUTPUT = ROOT / "src" / "slides_thief" / "product_metadata.py"
TYPESCRIPT_OUTPUT = ROOT / "site" / "app" / "product-metadata.ts"
PUBLIC_OUTPUT = ROOT / "site" / "public" / "product-metadata.json"
VERSION_PATTERN = re.compile(r"^__version__\s*=\s*\"([^\"]+)\"\s*$", re.MULTILINE)


def load_metadata() -> dict:
    metadata = json.loads(SOURCE.read_text(encoding="utf-8"))
    version_match = VERSION_PATTERN.search(
        (ROOT / "src" / "slides_thief" / "__init__.py").read_text(encoding="utf-8")
    )
    if version_match is None or version_match.group(1) != metadata["version"]:
        raise SystemExit("metadata/product.json version must match src/slides_thief/__version__")
    return metadata


def derived_values(metadata: dict) -> tuple[dict[str, float], list[str], dict[str, list[float]]]:
    ratios = metadata["ratios"]
    ratio_presets = {item["id"]: item["ratio"] for item in ratios["presentation"]}
    paper_presets: set[str] = set()
    page_dimensions: dict[str, list[float]] = {}
    for item in ratios["paper"]:
        page_dimensions[item["id"]] = [item["width_points"], item["height_points"]]
        for alias in item["aliases"]:
            ratio_presets[alias] = item["ratio"]
            paper_presets.add(alias)
    return ratio_presets, sorted(paper_presets), page_dimensions


def render_python(metadata: dict) -> str:
    ratio_presets, paper_presets, page_dimensions = derived_values(metadata)
    return """# This file is generated by scripts/generate_product_metadata.py.\n# Edit metadata/product.json and regenerate.\n\n""" + (
        f"PRODUCT_METADATA = {pprint.pformat(metadata, sort_dicts=False, width=120)}\n\n"
        f"RATIO_PRESETS = {pprint.pformat(ratio_presets, sort_dicts=False, width=120)}\n\n"
        f"PAPER_PRESETS = frozenset({pprint.pformat(paper_presets, sort_dicts=False, width=120)})\n\n"
        f"PAPER_PAGE_DIMENSIONS = {pprint.pformat(page_dimensions, sort_dicts=False, width=120)}\n"
    )


def render_typescript(metadata: dict) -> str:
    serialized = json.dumps(metadata, ensure_ascii=False, indent=2)
    return (
        "// This file is generated by scripts/generate_product_metadata.py.\n"
        "// Edit metadata/product.json and regenerate.\n\n"
        f"export const PRODUCT_METADATA = {serialized} as const;\n"
    )


def render_public(metadata: dict) -> str:
    return json.dumps(metadata, ensure_ascii=False, indent=2) + "\n"


def expected_outputs(metadata: dict) -> dict[Path, str]:
    return {
        PYTHON_OUTPUT: render_python(metadata),
        TYPESCRIPT_OUTPUT: render_typescript(metadata),
        PUBLIC_OUTPUT: render_public(metadata),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    metadata = load_metadata()
    outputs = expected_outputs(metadata)
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            joined = ", ".join(str(path.relative_to(ROOT)) for path in stale)
            raise SystemExit(f"stale generated product metadata: {joined}")
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
