"""Generate runtime product metadata from the repository source of truth."""

from __future__ import annotations

import argparse
import json
import pprint
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "metadata" / "product.json"
PYTHON_OUTPUT = ROOT / "src" / "slides_thief" / "product_metadata.py"
TYPESCRIPT_OUTPUT = ROOT / "site" / "app" / "product-metadata.ts"
PUBLIC_OUTPUT = ROOT / "site" / "public" / "product-metadata.json"
VERSION_PATTERN = re.compile(r"^__version__\s*=\s*\"([^\"]+)\"\s*$", re.MULTILINE)


def load_metadata() -> dict:
    metadata = json.loads(SOURCE.read_text(encoding="utf-8"))
    version_match = VERSION_PATTERN.search(
        (ROOT / "src" / "slides_thief" / "__init__.py").read_text(encoding="utf-8")
    )
    if version_match is None or version_match.group(1) != metadata["version"]:
        raise SystemExit("metadata/product.json version must match src/slides_thief/__version__")
    return metadata


def derived_values(metadata: dict) -> tuple[dict[str, float], list[str], dict[str, list[float]]]:
    ratios = metadata["ratios"]
    ratio_presets = {item["id"]: item["ratio"] for item in ratios["presentation"]}
    paper_presets: set[str] = set()
    page_dimensions: dict[str, list[float]] = {}
    for item in ratios["paper"]:
        if "ratio" in item:
            raise SystemExit(f"paper preset {item['id']} must derive ratio from point dimensions")
        width_points = float(item["width_points"])
        height_points = float(item["height_points"])
        if width_points <= 0 or height_points <= 0:
            raise SystemExit(f"paper preset {item['id']} must have positive point dimensions")
        page_dimensions[item["id"]] = [width_points, height_points]
        paper_ratio = width_points / height_points
        for alias in item["aliases"]:
            ratio_presets[alias] = paper_ratio
            paper_presets.add(alias)
    return ratio_presets, sorted(paper_presets), page_dimensions


def render_python(metadata: dict) -> str:
    ratio_presets, paper_presets, page_dimensions = derived_values(metadata)
    return """# This file is generated by scripts/generate_product_metadata.py.\n# Edit metadata/product.json and regenerate.\n\n""" + (
        f"PRODUCT_METADATA = {pprint.pformat(metadata, sort_dicts=False, width=120)}\n\n"
        f"RATIO_PRESETS = {pprint.pformat(ratio_presets, sort_dicts=False, width=120)}\n\n"
        f"PAPER_PRESETS = frozenset({pprint.pformat(paper_presets, sort_dicts=False, width=120)})\n\n"
        f"PAPER_PAGE_DIMENSIONS = {pprint.pformat(page_dimensions, sort_dicts=False, width=120)}\n"
    )


def render_typescript(metadata: dict) -> str:
    serialized = json.dumps(metadata, ensure_ascii=False, indent=2)
    return (
        "// This file is generated by scripts/generate_product_metadata.py.\n"
        "// Edit metadata/product.json and regenerate.\n\n"
        f"export const PRODUCT_METADATA = {serialized} as const;\n"
    )


def render_public(metadata: dict) -> str:
    return json.dumps(metadata, ensure_ascii=False, indent=2) + "\n"


def render_format_table(metadata: dict, chinese: bool = False) -> str:
    header = "| 格式 | 网页版 | CLI |" if chinese else "| Format | Web app | CLI |"
    separator = "| --- | --- | --- |"
    rows = [header, separator]
    for item in metadata["input_formats"]:
        web = ("支持" if item["web"] else "不支持") if chinese else ("Yes" if item["web"] else "No")
        cli = ("支持" if item["cli"] else "不支持") if chinese else ("Yes" if item["cli"] else "No")
        rows.append(f"| {item['label']} | {web} | {cli} |")
    return "\n".join(rows)


def web_source_labels(metadata: dict) -> list[str]:
    return [
        item.get("label", item["id"])
        for item in metadata["ratios"]["web_source_base_formats"]
        if item["kind"] != "custom"
    ]


def paper_families(metadata: dict, predicate) -> list[str]:
    families = []
    for item in metadata["ratios"]["paper"]:
        if predicate(item) and item["family"] not in families:
            families.append(item["family"])
    return families


def paper_orientation_labels(metadata: dict, predicate) -> list[str]:
    return [f"{family} landscape/portrait" for family in paper_families(metadata, predicate)]


def web_feature_line(metadata: dict, chinese: bool = False) -> str:
    sources = web_source_labels(metadata)
    papers = paper_families(metadata, lambda item: item["web"])
    if chinese:
        return "\n".join(
            [
                f"- 原稿比例可选 {'、'.join(sources)} 或自定义数值；PDF 页面可匹配原稿，选用 {'、'.join(papers)} 横向或纵向纸张，或设置自定义宽高。",
                "- 页面留白使用所选填充色；默认“自动”模式从画面内容取色，无法确定时回退为白色。",
            ]
        )
    return (
        f"- Source aspect-ratio choices include {', '.join(sources)} and custom values. PDF pages can match the source, "
        f"use physical {', '.join(papers)} paper in either orientation, or use custom pixel dimensions.\n"
        "- Page margins use the selected fill color; Auto samples the slide content and falls back to white."
    )


def cli_summary_chinese(metadata: dict) -> str:
    cli_only_papers = "、".join(paper_families(metadata, lambda item: item["cli"] and not item["web"]))
    return (
        f"CLI 额外支持 {cli_only_papers} 纸张比例预设，并接受数字形式的原稿或页面比例（如 `1.777`）。"
        "CLI 中的纸张名称只指定长宽比，不指定 PDF 的实际物理尺寸。"
    )


def web_summary(metadata: dict, prefix: str) -> str:
    papers = ", ".join(paper_families(metadata, lambda item: item["web"]))
    cli_only_papers = ", ".join(
        paper_families(metadata, lambda item: item["cli"] and not item["web"])
    )
    if prefix == "README":
        return (
            f"The web app offers physical {papers} PDF paper presets in landscape and portrait, "
            "plus source-matched or custom-size pages. "
            f"The CLI additionally supports {cli_only_papers} aspect-ratio presets and numeric source/output ratios; "
            "its paper names do not set physical PDF page dimensions."
        )
    if prefix == "FAQ":
        return (
            "The web app can match the selected source ratio (including 16:10 or a custom ratio), "
            f"use physical {papers} paper in either orientation, or set custom pixel dimensions. "
            "Page margins use the selected fill color; Auto samples slide content and falls back to white."
        )
    if prefix == "SITE":
        return f"Web PDF pages can match the source, use physical {papers} paper in either orientation, or use custom pixel dimensions."
    source = web_source_labels(metadata)
    return (
        f"The web app accepts {', '.join(source)} and custom source ratios. Its PDF can match the source, "
        f"use physical {papers} paper in either orientation, or use custom pixel dimensions. "
        f"{cli_only_papers} is available only as a CLI paper-ratio preset."
    )


def cli_input_bullets(metadata: dict) -> str:
    lines = []
    for item in metadata["input_formats"]:
        if item["cli"]:
            suffix = " (converted with macOS `sips`)" if item["id"] == "heic-heif" else ""
            lines.append(f"- {item['label']}{suffix}")
    return "\n".join(lines)


def cli_input_sentence(metadata: dict) -> str:
    labels = [item["label"] for item in metadata["input_formats"] if item["cli"]]
    web_only = [item["label"] for item in metadata["input_formats"] if item["web"] and not item["cli"]]
    conversion = next(
        (item["label"] for item in metadata["input_formats"] if item["id"] == "heic-heif"),
        "HEIC / HEIF",
    )
    web_only_sentence = ", ".join(web_only) + " is web-only." if web_only else ""
    return ", ".join(labels[:-1]) + f", and {labels[-1]}. {web_only_sentence} {conversion} conversion uses macOS `sips`."


def cli_ratio_bullets(metadata: dict) -> str:
    ratios = metadata["ratios"]
    source_ids = ratios["cli_source_ids"]
    output_presentation_ids = [
        item["id"] for item in ratios["presentation"] if item["id"] in ratios["cli_output_ids"]
    ]
    paper_lines = []
    for family in paper_families(metadata, lambda item: item["cli"]):
        items = [item for item in ratios["paper"] if item["family"] == family and item["cli"]]
        landscape = next(item for item in items if item["orientation"] == "landscape")
        portrait = next(item for item in items if item["orientation"] == "portrait")
        family_token = f"`{family}` / " if family.lower() in landscape["aliases"] else ""
        paper_lines.append(f"{family_token}`{landscape['id']}`, `{portrait['id']}`")
    iso_lines = ", ".join(paper_lines[:-1])
    letter_line = paper_lines[-1]
    return "\n".join(
        [
            (
                f"- Source presentation ratios: `{source_ids[0]}` (default), "
                f"{', '.join(f'`{value}`' for value in source_ids[1:])}, or a numeric custom ratio"
            ),
            (
                f"- Output presentation ratios: `match-slide` (default), "
                f"{', '.join(f'`{value}`' for value in output_presentation_ids)}"
            ),
            f"- ISO paper ratio presets: {iso_lines}",
            f"- US Letter paper ratio presets: {letter_line}",
            f"- Custom source or output ratios: e.g. `{source_ids[-1]}` or a numeric decimal ratio (e.g. `1.777`)",
        ]
    )


def cli_ratio_sentence(metadata: dict) -> str:
    source_ids = metadata["ratios"]["cli_source_ids"]
    families = ", ".join(paper_families(metadata, lambda item: item["cli"]))
    presentation = f"{source_ids[0]} (default)"
    if len(source_ids) > 1:
        presentation += f", {', '.join(source_ids[1:])}"
    return (
        f"Presentation source ratios: {presentation}. Paper ratio presets: {families} in landscape and portrait. "
        "Numeric custom ratios such as 1.777 work for source or output. "
        "CLI paper names set aspect ratio, not physical PDF page size; CLI paper margins are white."
    )


def generated_document_outputs(metadata: dict) -> dict[Path, str]:
    format_en = render_format_table(metadata)
    format_zh = render_format_table(metadata, chinese=True)
    outputs: dict[Path, str] = {}
    document_blocks = {
        ROOT / "README.md": {
            "formats-en": format_en,
            "web-feature-en": web_feature_line(metadata),
            "web-summary-en": web_summary(metadata, "README"),
        },
        ROOT / "README.zh-CN.md": {
            "formats-zh": format_zh,
            "web-feature-zh": web_feature_line(metadata, chinese=True),
            "cli-summary-zh": cli_summary_chinese(metadata),
        },
        ROOT / "docs" / "faq.md": {
            "formats-en": format_en,
            "web-summary-en": web_summary(metadata, "FAQ"),
            "cli-summary-en": f"The CLI adds {', '.join(paper_families(metadata, lambda item: item['cli'] and not item['web']))} paper-ratio presets and accepts numeric custom source and output ratios. Its paper names do not set physical PDF page dimensions.",
        },
        ROOT / "site" / "README.md": {
            "formats-en": format_en,
            "web-summary-en": web_summary(metadata, "SITE"),
        },
        ROOT / "docs" / "cli.md": {
            "cli-input-en": cli_input_bullets(metadata),
            "cli-ratios-en": cli_ratio_bullets(metadata),
            "web-summary-en": web_summary(metadata, "CLI"),
        },
        ROOT / "site" / "public" / "llms.txt": {
            "llms-core-en": "\n".join(
                [
                    f"- Web formats: {', '.join(item['label'] for item in metadata['input_formats'] if item['web'])}. CLI formats: {', '.join(item['label'] for item in metadata['input_formats'] if item['cli'])}.",
                    f"- Web source formats: {', '.join(web_source_labels(metadata)[:-1])}, {web_source_labels(metadata)[-1]}, and custom ratios.",
                    f"- Web PDF layouts: match the selected source format, physical {', '.join(paper_families(metadata, lambda item: item['web']))} paper, or a custom page size.",
                ]
            )
        },
        ROOT / "site" / "public" / "llms-full.txt": {
            "llms-web-en": "\n".join(
                [
                    f"- Source formats: {web_source_labels(metadata)[0]} by default, with explicit {', '.join(web_source_labels(metadata)[1:])}, and custom ratios.",
                    f"- PDF layouts: match the selected source format, physical {', '.join(paper_orientation_labels(metadata, lambda item: item['web']))} paper, or custom pixel dimensions. Page margins use the selected fill color; Auto samples slide content and falls back to white.",
                ]
            ),
            "cli-input-en": cli_input_sentence(metadata),
            "cli-ratios-en": cli_ratio_sentence(metadata),
        },
        ROOT / "PRODUCT.md": {
            "product-capabilities-en": "\n".join(
                [
                    f"- Source aspect-ratio choices include {', '.join(web_source_labels(metadata))} and custom values.",
                    f"- PDF pages can match the source, use physical {', '.join(paper_families(metadata, lambda item: item['web']))} paper in landscape or portrait, or use custom pixel dimensions.",
                    f"- Supports {', '.join(item['label'] for item in metadata['input_formats'] if item['web'])} in the web app.",
                ]
            )
        },
    }
    for path, blocks in document_blocks.items():
        content = path.read_text(encoding="utf-8")
        for marker, block in blocks.items():
            start = f"<!-- BEGIN GENERATED: {marker} -->"
            end = f"<!-- END GENERATED: {marker} -->"
            pattern = re.compile(re.escape(start) + r"[\s\S]*?" + re.escape(end))
            replacement = f"{start}\n{block}\n{end}"
            content, count = pattern.subn(replacement, content)
            if count != 1:
                raise SystemExit(f"expected exactly one generated block {marker} in {path.relative_to(ROOT)}")
        outputs[path] = content
    return outputs


def expected_outputs(metadata: dict) -> dict[Path, str]:
    outputs = {
        PYTHON_OUTPUT: render_python(metadata),
        TYPESCRIPT_OUTPUT: render_typescript(metadata),
        PUBLIC_OUTPUT: render_public(metadata),
    }
    outputs.update(generated_document_outputs(metadata))
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    metadata = load_metadata()
    outputs = expected_outputs(metadata)
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            joined = ", ".join(str(path.relative_to(ROOT)) for path in stale)
            raise SystemExit(f"stale generated product metadata: {joined}")
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
